title: "Kenza Idir – Data & AI Consultant"
logo: "/Photo-Kenza-IDIR.png"
description: "Consultante en data et intelligence artificielle | Analyse de données, visualisation, automatisation et formation"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
