title: "Kenza Idir – Data and AI Consultant"
logo: "/Photo-Kenza-IDIR.png"
description: |
  <b> Contact</b><br>
  📧 <a href="mailto:idirkenza749@gmail.com">idirkenza749@gmail.com</a><br>
  🔗 <a href="https://www.linkedin.com/in/kidir/" target="_blank">LinkedIn</a>

theme: jekyll-theme-minimal
show_downloads: false

github:
  is_project_page: false
