title: "Kenza Idir – Data & AI Consultant"
logo: "/Photo-Kenza-IDIR.png"
description: |
      <h3> Contacts </h3>
  📧 <a href="mailto:idirkenza749@gmail.com">idirkenza749@gmail.com</a>  
  🔗 <a href="https://www.linkedin.com/in/kidir/" target="_blank">LinkedIn</a>

theme: jekyll-theme-minimal
show_downloads: false

github:
  is_project_page: false
